name: stomp
author: Tom Yeh <tomyeh@rikulo.org>
version: 0.7.1
homepage: https://github.com/rikulo/stomp
description: Dart STOMP client for easy messaging interoperability.
documentation: http://api.rikulo.org/stomp/latest
environment:
  sdk: '>=1.0.0'
dependencies:
  quiver: any
  unittest: any
